import type { Week } from "./types";

const uid = () => Math.random().toString(36).slice(2, 10);

export const seedWeek: Week = {
  id: uid(),
  label: "2026.5.20.",
  projects: [
    {
      id: uid(),
      status: "개찰",
      name: "154kV 상운S/S",
      leader: "추영욱",
      submitDate: "4/13",
      interviewDate: "4/21",
      bidDate: "5/18",
      fee: "23.6",
      note: "-안전 김영국",
    },
    {
      id: uid(),
      status: "개찰",
      name: "충주 시민의 숲 목재문화관",
      leader: "김기욱",
      submitDate: "4/23",
      interviewDate: "4/24",
      bidDate: "추후",
      fee: "19.2",
      note: "-건축 윤권수",
    },
    {
      id: uid(),
      status: "개찰",
      name: "서원 국민체육센터",
      leader: "김종완",
      submitDate: "4/20",
      interviewDate: "4/24",
      bidDate: "추후",
      fee: "20",
      note: "",
    },
    {
      id: uid(),
      status: "진행중",
      name: "의정부법조타운 S-2BL 및 S-3BL",
      leader: "황창석",
      submitDate: "5/6",
      interviewDate: "5/21",
      bidDate: "5/21",
      fee: "194.5",
      note: "-건축 모길주 -토목 장정환\n-안전 노태락 -기계 정관희",
    },
    {
      id: uid(),
      status: "진행중",
      name: "154kV 학운변전소",
      leader: "이영춘",
      submitDate: "5/6",
      interviewDate: "추후",
      bidDate: "5/20",
      fee: "23.6",
      note: "-안전 허석준",
    },
    {
      id: uid(),
      status: "진행중",
      name: "시제물품 보관창고 신축 외 4건",
      leader: "김기욱",
      submitDate: "5/1",
      interviewDate: "5/4",
      bidDate: "5/20",
      fee: "13.9",
      note: "-건축 윤권수",
    },
    {
      id: uid(),
      status: "진행중",
      name: "쌍문1동 공공복합청사",
      leader: "신경철",
      submitDate: "5/13",
      interviewDate: "5/19",
      bidDate: "5/27",
      fee: "28.5",
      note: "-건축 박종혁",
    },
    {
      id: uid(),
      status: "진행중",
      name: "26-A-00부대(A005)",
      leader: "김지훈",
      submitDate: "5/6",
      interviewDate: "5/14",
      bidDate: "5/19",
      fee: "18.7",
      note: "-건축 박재흥 -토목 오인환",
    },
  ],
  upcoming: [],
  members: [
    { id: uid(), role: "책임", name: "추영욱", org: "" },
    { id: uid(), role: "책임", name: "김종완", org: "" },
    { id: uid(), role: "책임", name: "황창석", org: "" },
    { id: uid(), role: "책임", name: "김기욱", org: "" },
    { id: uid(), role: "책임", name: "이영춘", org: "" },
    { id: uid(), role: "책임", name: "신경철", org: "" },
    { id: uid(), role: "책임", name: "김지훈", org: "" },
    { id: uid(), role: "건축", name: "윤권수", org: "" },
    { id: uid(), role: "건축", name: "모길주", org: "KD" },
    { id: uid(), role: "건축", name: "박재흥", org: "" },
    { id: uid(), role: "건축", name: "박종혁", org: "" },
    { id: uid(), role: "토목", name: "장정환", org: "ITM" },
    { id: uid(), role: "토목", name: "오인환", org: "" },
    { id: uid(), role: "안전", name: "김영국", org: "" },
    { id: uid(), role: "안전", name: "노태락", org: "ITM" },
    { id: uid(), role: "안전", name: "허석준", org: "" },
    { id: uid(), role: "기계", name: "정관희", org: "" },
  ],
  etc: "",
};
